version: '3.8'

services:
  #  eureka-server:
  #    image: serzhe1/eureka-server:1.1
  #    ports:
  #      - "8761:8761"
  #  api-gateway:
  #    image: serzhe1/api-gateway:1.0
  #    environment:
  #      - EUREKA.CLIENT.SERVICE-URL.DEFAULTZONE=http://eureka-server:8091/eureka
  #    ports:
  #      - "8092:8092"
  #    depends_on:
  #      - eureka-server
  #  cms:
  #    build:
  #      context: ./
  #    depends_on:
  #      - eureka-server
  #      - db
  #    environment:
  #      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/postgres
  #      - SPRING_DATASOURCE_USERNAME=postgres
  #      - SPRING_DATASOURCE_PASSWORD=psql123
  #      - EUREKA.CLIENT.SERVICE-URL.DEFAULTZONE=http://eureka-server:8091/eureka
  #    ports:
  #      - "8090:8090"
  #  /////////////////////////////////////////////////////////////////////////////////////////////////////////////////////

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: psql123
      POSTGRES_DB: postgres
    volumes:
      - ./data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "2345:5432"
  keycloak:
    image: quay.io/keycloak/keycloak:18.0.0
    command: start-dev
    environment:
      KC_DB: postgres
      KC_DB_URL_HOST: auth-db
      KC_DB_URL_DATABASE: keycloak
      KC_DB_PASSWORD: password
      KC_DB_USERNAME: keycloak
      KC_DB_SCHEMA: public
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    ports:
      - "8555:8080"
    depends_on:
      auth-db:
        condition: service_healthy
    networks:
      - keycloak_network

  auth-db:
    image: postgres
    command: postgres -c 'max_connections=200'
    volumes:
      - pgdata_keycloak:/var/lib/postgres/data
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: password
    healthcheck:
      test: "exit 0"
    ports:
      - "5432:5432"
    networks:
      - keycloak_network
volumes:
  pgdata_keycloak:
networks:
  keycloak_network:
    driver: bridge

