server:
  port: 8091
  servlet:
    context-path: /article-service
spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://localhost:8555/realms/edpl/protocol/openid-connect/certs
  datasource:
    url: jdbc:postgresql://localhost:2345/article
    username: postgres
    password: psql123
  data:
    web:
      pageable:
        one-indexed-parameters: true
        default-page-size: 10
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER
  main:
    allow-circular-references: true
  jpa:
    hibernate:
      ddl-auto: update
    database: POSTGRESQL
    show-sql: false
    properties:
      hibernate:
        jdbc:
          time_zone: UTC
springdoc:
  swagger-ui:
    path: /swagger-ui
---
spring:
  config:
    activate:
      on-profile: deb
logging:
  level:
    root: DEBUG
