server:
  port: 8091
  servlet:
    context-path: /article-service
spring:
  security:
    oauth2:
      client:
        provider:
          my-keycloak-provider:
            issuer-uri: http://localhost:8555/realms/edpl
            authorization-uri: http://localhost:8555/realms/edpl/protocol/openid-connect/auth
            token-uri: http://localhost:8555/realms/edpl/protocol/openid-connect/token
            user-info-uri: http://localhost:8555/realms/edpl/protocol/openid-connect/userinfo
            jwk-set-uri: http://localhost:8555/realms/edpl/protocol/openid-connect/certs
            user-name-attribute: preferred_username
            user-info-authentication-method: header
        registration:
          keycloak-spring-gateway-client:
            provider: my-keycloak-provider
            client-id: spring-gateway-application
            client-secret: N4rwld6zCy8Ra9l5Dw0QdjoeQCWYQSyd
            authorization-grant-type: authorization_code
            redirect-uri: "{baseUrl}/login/oauth2/code/keycloak"
            scope: openid
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8555/realms/edpl
          jwk-set-uri: http://localhost:8555/realms/edpl/protocol/openid-connect/certs
  datasource:
    url: jdbc:postgresql://localhost:2345/article
    username: postgres
    password: psql123
  data:
    web:
      pageable:
        one-indexed-parameters: true
        default-page-size: 10
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER
  main:
    allow-circular-references: true
    allow-cors: false
  servlet:
    cors:
      enabled: false
  jpa:
    hibernate:
      ddl-auto: update
    database: POSTGRESQL
    show-sql: false
    properties:
      hibernate:
        jdbc:
          time_zone: UTC
springdoc:
  swagger-ui:
    path: /swagger-ui
auth:
  whitelist:
    /v2/**
    /v3/**
    /swagger-resources/**
    /swagger-ui/**
    /
    /documentation/**

#jwt:
#  auth:
#    converter: spring-gateway-application
#    principal-attribute: preferred_username
---
spring:
  config:
    activate:
      on-profile: deb
logging:
  level:
    root: DEBUG
