server:
  port: 8090

spring:
  main:
    allow-circular-references: true
  application:
    name: course-manager
  datasource:
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: psql123
    url: jdbc:postgresql://192.168.242.104:2345/postgres
  jpa:
    hibernate:
      ddl-auto: none
springdoc:
  swagger-ui:
    path: /swagger-ui
eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: http://localhost:8761/eureka