server:
  port: 8090
  servlet:
    context-path: /course-manager

spring:
  application:
    name: course-manager-service
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/course
    username: postgres
    password: psql123
  jpa:
    hibernate:
      ddl-auto: update
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8091/eureka