spring:
  cloud:
    gateway:
      routes:
        - id: article-service
          uri: http://localhost:8091
          predicates:
            - Path=/article-service/**
          filters:
            - TokenRelay
  security:
    oauth2:
      client:
        provider:
          my-keycloak-provider:
            user-name-attribute: preferred_username
            issuer-uri: http://localhost:8555/realms/edpl
        registration:
          keycloak-spring-gateway-client:
            provider: my-keycloak-provider
            scope: openid
            client-id: spring-gateway-application
            client-secret: N4rwld6zCy8Ra9l5Dw0QdjoeQCWYQSyd
            authorization-grant-type: authorization_code
            redirect-uri: "{baseUrl}/login/oauth2/code/keycloak"

# Enable these to debug the Authorization flow
logging:
  level:
    org:
      springframework:
        security: DEBUG

server:
  port: 9090

management:
  endpoints:
    web:
      exposure:
        include: "*"